spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        url: jdbc:postgresql://localhost:5432/restaurant
        password: mirlan001m.
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: mirlan&java12